# Site settings
title: Belvedere Piscinas
email: 
description: > # this means to ignore newlines until "baseurl:"
  Conheça este serviço de limpeza de piscinas!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://belvederepiscinas.com.br" # the base hostname & protocol for your site
instagram_username: belvederepiscinas

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]